version: "2.6.1"
services:

  # mysql:
  #   image: mysql
  #   ports:
  #     - 3307:3306
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Gat64mec
  #     MYSQL_DATABASE: shopping
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql


  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Gat64mec

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Gat64mec
      ME_CONFIG_MONGODB_SERVER: mongodb


    
